# -*- coding: utf-8 -*-
"""Linear_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-waQA3QkWSXNCZCrbRJSu0Zw9It7FSu

Giả thiết: Giá khởi điểm của một căn nhà là 50k, với mỗi một phòng, giá trị căn nhà tăng thêm 50k. Ví dụ: 1 căn nhà không có phòng có giá 50k, căn nhà 1 phòng sẽ có giá 100k,...
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras

model = keras.Sequential([keras.layers.Dense(units=1, input_shape = [1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([0.0,1.0,2.0,3.0,5.0,6.0,8.0,9.0],dtype=float)
ys = np.array([0.50,1.0,1.5,2.0,3.0,3.5,4.5,5.0], dtype = float)

model.fit(xs,ys, epochs = 500)

print(model.predict([7.0])*100)